builds:
  - goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: amd64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - description: Zsh Fuzzy Completion Plugin
    tap:
      owner: Ryooooooga
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/Ryooooooga/qwy
    install: bin.install "qwy"
    test: system "#{bin}/qwy", "--version"
